name: Main checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux-main-checks:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test-linux64
  macos-latest:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test
        run: |
          node cli.js --os=mac64arm --engines=escargot
      - name: Confirm
        run: |
          echo "print('hello world!');" > test.js
          ls -l ~/.jsvu/bin
          ls -l ~/.jsvu/engines/escargot
          ~/.jsvu/bin/escargot test.js
  macos-12:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install 
      - name: Test
        run: |
          npm link
          jsvu --os=mac64arm --engines=escargot
      - name: Confirm
        run: |
          echo "print('hello world!');" > test.js
          ls -l ~/.jsvu/bin
          ls -l ~/.jsvu/engines/escargot
          ~/.jsvu/bin/escargot test.js
